window.drupalTranslations = {
    "strings": {
        "": {
            "Home": "Hjem",
            "Next": "N\u00e6ste",
            "closed": "lukket",
            "Cancel": "Annull\u00e9r",
            "Disabled": "Deaktiveret",
            "Enabled": "Aktiveret",
            "Edit": "Redig\u00e9r",
            "Link": "Link",
            "Image": "Image",
            "Save": "Gem",
            "Open": "\u00c5ben",
            "Sunday": "S\u00f8ndag",
            "Monday": "Mandag",
            "Tuesday": "Tirsdag",
            "Wednesday": "Onsdag",
            "Thursday": "Torsdag",
            "Friday": "Fredag",
            "Saturday": "L\u00f8rdag",
            "Add": "Tilf\u00f8j",
            "Continue": "Forts\u00e6t",
            "Done": "F\u00e6rdig",
            "OK": "O.k.",
            "Prev": "Forrige",
            "Mon": "man",
            "Tue": "tir",
            "Wed": "ons",
            "Thu": "tor",
            "Fri": "fre",
            "Sat": "l\u00f8r",
            "Sun": "s\u00f8n",
            "May": "maj",
            "Close": "Luk",
            "Add group": "Tilf\u00f8j gruppe",
            "Show": "Vis",
            "Select all rows in this table": "V\u00e6lg alle r\u00e6kker i tabellen",
            "Deselect all rows in this table": "Frav\u00e6lg alle r\u00e6kker i tabellen",
            "Today": "I dag",
            "Jan": "jan",
            "Feb": "feb",
            "Mar": "mar",
            "Apr": "apr",
            "Jun": "jun",
            "Jul": "jul",
            "Aug": "aug",
            "Sep": "sep",
            "Oct": "okt",
            "Nov": "nov",
            "Dec": "dec",
            "Extend": "Udvid",
            "Su": "S\u00f8",
            "Mo": "Ma",
            "Tu": "Ti",
            "We": "On",
            "Th": "To",
            "Fr": "Fr",
            "Sa": "L\u00f8",
            "Changed": "\u00c6ndret",
            "Not published": "Ikke udgivet",
            "Loading...": "Indl\u00e6ser...",
            "Apply": "Udf\u00f8r",
            "Please wait...": "Vent venligst\u2026",
            "Hide": "Skjul",
            "1 new comment\u0003@count new comments": "1 ny kommentar\u0003@count nye kommentarer",
            "Unlink": "Fjern link",
            "Not promoted": "Ikke forfremmet",
            "mm\/dd\/yy": "mm\/dd\/yy",
            "Quick edit": "Hurtig redigering",
            "button": "knap",
            "Edit Link": "Redig\u00e9r link",
            "Remove group": "Fjern gruppe",
            "By @name on @date": "Af @name, @date",
            "By @name": "Af @name",
            "Not in menu": "Ikke i menu",
            "Alias: @alias": "Alias: @alias",
            "No alias": "Intet alias",
            "@label": "@label",
            "New revision": "Ny version",
            "Drag to re-order": "Tr\u00e6k for at (om)sortere",
            "Changes made in this table will not be saved until the form is submitted.": "\u00c6ndringer i tabellen bliver ikke gemt, f\u00f8r du indsender formularen.",
            "Discard changes": "Fortryd \u00e6ndringer",
            "Show description": "Vis beskrivelse",
            "New group": "Ny gruppe",
            "Lock": "L\u00e5s",
            "Saving": "Gemmer",
            "This permission is inherited from the authenticated user role.": "Denne tilladelse er arvet fra den godkendte brugerrolle.",
            "No revision": "Ingen version",
            "Requires a title": "Kr\u00e6ver en titel",
            "Not restricted": "Ikke begr\u00e6nset",
            "(active tab)": "(aktiv fane)",
            "An AJAX HTTP error occurred.": "Der opstod en AJAX HTTP-fejl.",
            "HTTP Result Code: !status": "HTTP resultatkode: !status",
            "An AJAX HTTP request terminated abnormally.": "En AJAX HTTP-foresp\u00f8rgsel afsluttede p\u00e5 unormal vis.",
            "Debugging information follows.": "Information til fejls\u00f8gning f\u00f8lger.",
            "Path: !uri": "Sti: !uri",
            "StatusText: !statusText": "StatusText: !statusText",
            "ResponseText: !responseText": "ResponseText: !responseText",
            "ReadyState: !readyState": "ReadyState: !readyState",
            "Restricted to certain pages": "Begr\u00e6nset til bestemte sider",
            "The block cannot be placed in this region.": "Blokken kan ikke placeres i denne region.",
            "Hide summary": "Skjul resum\u00e9",
            "Edit summary": "Redig\u00e9r resum\u00e9",
            "Don\u0027t display post information": "Vis ikke information om indl\u00e6gget",
            "Unlock": "L\u00e5s op",
            "Collapse": "Klap sammen",
            "The selected file %filename cannot be uploaded. Only files with the following extensions are allowed: %extensions.": "Den valgte fil %filename kan ikke uploades. Kun filer med f\u00f8lgende filendelser er tilladt: %extensions.",
            "Show row weights": "Vis r\u00e6kkev\u00e6gte",
            "Hide row weights": "Skjul r\u00e6kkev\u00e6gte",
            "Apply (all displays)": "Anvend (alle displays)",
            "Apply (this display)": "Anvend (dette display)",
            "Revert to default": "Gendan til standard",
            "Hide description": "Skjul beskrivelse",
            "You have unsaved changes": "Du har \u00e6ndringer, som ikke er blevet gemt",
            "Needs to be updated": "Skal opdateres",
            "Does not need to be updated": "Beh\u00f8ver ikke at blive opdateret",
            "Show all columns": "Vis alle kolonner",
            "Show table cells that were hidden to make the table fit within a small screen.": "Vis tabelceller som var skjult for at f\u00e5 tabellen til at passe p\u00e5 en lille sk\u00e6rm.",
            "List additional actions": "Vis yderligere handlinger",
            "Flag other translations as outdated": "Mark\u00e9r andre overs\u00e6ttelser som for\u00e6ldede",
            "Do not flag other translations as outdated": "Mark\u00e9r ikke andre overs\u00e6ttelser som for\u00e6ldede",
            "opened": "\u00e5bnet",
            "Horizontal orientation": "Horisontal placering",
            "Vertical orientation": "Vertikal placering",
            "Tray orientation changed to @orientation.": "Bakkeplacering \u00e6ndret til @orientation.",
            "You have unsaved changes.": "Du har \u00e6ndringer, som ikke er blevet gemt.",
            "No styles configured": "Ingen styles konfigureret",
            "@count styles configured": "@count styles konfigureret",
            "@action @title configuration options": "Indstillinger for @action @title",
            "Tabbing is no longer constrained by the Contextual module.": "Tabbing er ikke l\u00e6ngere begr\u00e6nset af Contextual-modulet.",
            "Tabbing is constrained to a set of @contextualsCount and the edit mode toggle.": "Tabbing er begr\u00e6nset af @contextualsCount og redigeringstilstanden.",
            "Press the esc key to exit.": "Tryk p\u00e5 esc for at afslutte.",
            "@count contextual link\u0003@count contextual links": "@count kontekstuelt link\u0003@count kontekstuellle links",
            "Based on the text editor configuration, these tags have automatically been added: \u003Cstrong\u003E@tag-list\u003C\/strong\u003E.": "Disse tags er blevet tilf\u00f8jet automatisk p\u00e5 basis af indstillingerne for tekst-editoren: \u003Cstrong\u003E@tag-list\u003C\/strong\u003E.",
            "!tour_item of !total": "!tour_item af !total",
            "End tour": "Slut tour",
            "Uploads disabled": "Uploads deaktiveret",
            "Uploads enabled, max size: @size @dimensions": "Uploads er aktiveret, maksimal st\u00f8rrelse: @size @dimensions",
            "Discard changes?": "Fortryd \u00e6ndringer?",
            "The toolbar cannot be set to a horizontal orientation when it is locked.": "V\u00e6rkt\u00f8jslinjen kan ikke s\u00e6ttes til horisontal orientering n\u00e5r den er l\u00e5st.",
            "Could not load the form for \u003Cq\u003E@field-label\u003C\/q\u003E, either due to a website problem or a network connection problem.\u003Cbr\u003EPlease try again.": "Kunne ikke indl\u00e6se formularen for \u003Cq\u003E@field-label\u003C\/q\u003E, enten p\u00e5 grund af et problem med websitet eller et netv\u00e6rksproblem.\u003Cbr\u003EFors\u00f8g venligst igen.",
            "Your changes to \u003Cq\u003E@entity-title\u003C\/q\u003E could not be saved, either due to a website problem or a network connection problem.\u003Cbr\u003EPlease try again.": "Dine \u00e6ndringer til \u003Cq\u003E@entity-title\u003C\/q\u003E kunne ikke gemmes, enten p\u00e5 grund af et problem med websitet eller et netv\u00e6rksproblem.\u003Cbr\u003EFors\u00f8g venligst igen.",
            "Hide group names": "Skjul gruppenavne",
            "Show group names": "Vis gruppenavne",
            "@groupName button group in position @position of @positionCount in row @row of @rowCount.": "Knapgruppe @groupName p\u00e5 position @position af @positionCount p\u00e5 r\u00e6kke @row af @rowCount.",
            "Press the down arrow key to create a new row.": "Tryk pil ned for at oprette en ny r\u00e6kke.",
            "@name @type.": "@name @type.",
            "Press the down arrow key to activate.": "Tryk pil ned for at aktivere.",
            "@name @type in position @position of @positionCount in @groupName button group in row @row of @rowCount.": "@name @type p\u00e5 position @position af @positionCount i knapgruppen @groupName p\u00e5 r\u00e6kke @row af @rowCount.",
            "Press the down arrow key to create a new button group in a new row.": "Tryk pil ned for at oprette en ny knapgruppe i en ny r\u00e6kke.",
            "This is the last group. Move the button forward to create a new group.": "Dette er den sidste gruppe. Flyt knappen frem for at oprette en ny gruppe.",
            "The \u0022@name\u0022 button is currently enabled.": "Knappen @name er i \u00f8jebliket aktiveret.",
            "Use the keyboard arrow keys to change the position of this button.": "Brug piletasterne p\u00e5 tastatures for at \u00e6ndre knappens position.",
            "Press the up arrow key on the top row to disable the button.": "Tryk p\u00e5 pil-op i den \u00f8verste r\u00e6kke for at deaktivere knappen.",
            "The \u0022@name\u0022 button is currently disabled.": "The \u0022@name\u0022 button is currently disabled.",
            "Use the down arrow key to move this button into the active toolbar.": "Brug pil-ned for at flytte denne knap til den aktive v\u00e6rkt\u00f8jslinje.",
            "This @name is currently enabled.": "Dette @name er i \u00f8jebliket deaktiveret.",
            "Use the keyboard arrow keys to change the position of this separator.": "Brug piletasterne p\u00e5 tastaturet for at \u00e6ndre skillelinjens position.",
            "Separators are used to visually split individual buttons.": "Skillelinjer bruger til at adskille individuelle knapper visuelt.",
            "This @name is currently disabled.": "Dette @name er i \u00f8jebliket deaktiveret.",
            "Use the down arrow key to move this separator into the active toolbar.": "Brug pil-ned for at flytte denne skillelinje til den aktive v\u00e6rkt\u00f8jslinje.",
            "You may add multiple separators to each button group.": "Du kan tilf\u00f8je flere skillelinjer til hver knapgruppe.",
            "Please provide a name for the button group.": "Angive venligst et navn p\u00e5 knapgruppen.",
            "Button group name": "Navn p\u00e5 knapgruppe",
            "Editing the name of the new button group in a dialog.": "Redig\u00e9r navnet p\u00e5 den nye knapgruppe i en dialogboks.",
            "Editing the name of the \u0022@groupName\u0022 button group in a dialog.": "Redig\u00e9r navnet p\u00e5 knapgruppen \u0022@groupName\u0022 i en dialogboks.",
            "Place a button to create a new button group.": "Plac\u00e9r en knap for at oprette en ny knapgruppe.",
            "Add a CKEditor button group to the end of this row.": "Tilf\u00f8j en CKEditor knapgruppe i slutningen af denne r\u00e6kke.",
            "Change text format?": "Skift tekstformat?",
            "Rich Text Editor, !label field": "Rich Text Editor, !label field",
            "Tray \u0022@tray\u0022 @action.": "Bakke \u0022@tray\u0022 @action.",
            "Tray @action.": "Bakke @action.",
            "Hide lower priority columns": "Skjul kolonner med lav prioritet",
            "!modules modules are available in the modified list.": "!modules moduler er tilg\u00e6ngelige i den modificerede liste.",
            "The callback URL is not local and not trusted: !url": "Callback-URLen er ikke lokal og er ikke trov\u00e6rdig: !url",
            "CustomMessage: !customMessage": "CustomMessage: !customMessage",
            "Network problem!": "Netv\u00e6rksproblem!",
            "Authored on @date": "Skrevet den @date",
            "item": "vare",
            "items": "elementer",
            "Insert this token into your form": "Inds\u00e6t dette token i din formular",
            "First click a text field to insert your tokens into.": "Klik p\u00e5 et tekstfelt som tokens skal s\u00e6ttes ind i.",
            "Automatic alias": "Automatisk alias"
        },
        "Long month name": {
            "January": "januar",
            "February": "februar",
            "March": "marts",
            "April": "april",
            "May": "maj",
            "June": "juni",
            "July": "juli",
            "August": "august",
            "September": "september",
            "October": "oktober",
            "November": "november",
            "December": "december"
        }
    },
    "pluralFormula": {
        "1": 0,
        "default": 1
    }
};;